// Shared color swatch definitions — used by ProductCard and ProductDetailClient.
// Keep these in sync with product.colors values from Shopify/localProducts.

export const PRODUCT_COLORS: Record<string, { name: string; value: string }[]> = {
  'trailblazing-fleece': [
    { name: 'Wildflower',  value: '#E8A0B8' },
    { name: 'Golden Hour', value: '#E8C84A' },
  ],
  'juniper-pant': [
    { name: 'Birch',       value: '#E4DCC8' },
    { name: 'Olive',       value: '#7A8352' },
  ],
  'alpine-baby-tee': [
    { name: 'Petal',       value: '#F2C4CE' },
    { name: 'Solstice',    value: '#D4A843' },
  ],
  // Order matches the image order in products.ts (berry → gingham → retro print)
  'sierra-shorts': [
    { name: 'Jam',      value: '#8E3A56' },
    { name: 'Picnic',   value: '#E7A6C0' },
    { name: 'Confetti', value: 'linear-gradient(135deg, #F2E9DA 0 25%, #A8C484 25% 50%, #7A5C3E 50% 75%, #E28FB4 75% 100%)' },
  ],
};

// Explicit gallery images per colorway (used when a product has different
// numbers of photos per color). Lead/front shot first.
const PP = '/images-2/model';
export const PRODUCT_COLOR_IMAGES: Record<string, Record<string, string[]>> = {
  // Files are numbered in gallery order by scripts/import-product-photos.py —
  // -1 is the lead shot (full-body front), then back / lifestyle / detail.
  // Re-running that script regenerates them, so keep these lists in sync with
  // the PLAN dict there rather than reordering by hand.
  'sierra-shorts': {
    Jam:      [`${PP}/jam-1.jpg`, `${PP}/jam-2.jpg`, `${PP}/jam-3.jpg`, `${PP}/jam-4.jpg`, `${PP}/jam-5.jpg`, `${PP}/jam-6.jpg`],
    // Picnic gained a fifth frame when it moved off the older "Pink Shorts"
    // HEICs onto the retouched "fixed photos" set — the same source Jam and
    // Confetti use, so all three colourways finally match each other.
    Picnic:   [`${PP}/picnic-1.jpg`, `${PP}/picnic-2.jpg`, `${PP}/picnic-3.jpg`, `${PP}/picnic-4.jpg`, `${PP}/picnic-5.jpg`],
    Confetti: [`${PP}/confetti-1.jpg`, `${PP}/confetti-2.jpg`, `${PP}/confetti-3.jpg`, `${PP}/confetti-4.jpg`, `${PP}/confetti-5.jpg`],
  },
  'juniper-pant': {
    Birch: [`${PP}/birch-1.jpg`, `${PP}/birch-2.jpg`, `${PP}/birch-3.jpg`, `${PP}/birch-4.jpg`, `${PP}/birch-5.jpg`, `${PP}/birch-6.jpg`, `${PP}/birch-7.jpg`],
    Olive: [`${PP}/olive-1.jpg`, `${PP}/olive-2.jpg`, `${PP}/olive-3.jpg`, `${PP}/olive-4.jpg`],
  },
};

// ─── Lifestyle strip ────────────────────────────────────────────────────────
//
// Outdoor shots — trail, rocks, a clothesline — shown in a small row further
// down the product page, under the description.
//
// Kept out of PRODUCT_COLOR_IMAGES on purpose. The main gallery is white-
// background studio frames whose job is to show the garment accurately; a
// backlit hillside dropped into that sequence makes the studio shots look
// inconsistent and the outdoor ones look like an accident. Separating them
// lets each do its own job.
//
// Generated by LIFESTYLE_PLAN in scripts/import-product-photos.py, at a
// smaller max edge than the gallery since these render as thumbnails.
const LP = '/images-2/lifestyle';
export const PRODUCT_LIFESTYLE_IMAGES: Record<string, Record<string, string[]>> = {
  'sierra-shorts': {
    Jam:      [`${LP}/jam-life-1.jpg`, `${LP}/jam-life-2.jpg`, `${LP}/jam-life-3.jpg`, `${LP}/jam-life-4.jpg`],
    Picnic:   [`${LP}/picnic-life-1.jpg`, `${LP}/picnic-life-2.jpg`, `${LP}/picnic-life-3.jpg`, `${LP}/picnic-life-4.jpg`, `${LP}/picnic-life-5.jpg`, `${LP}/picnic-life-6.jpg`],
    Confetti: [`${LP}/confetti-life-1.jpg`, `${LP}/confetti-life-2.jpg`, `${LP}/confetti-life-3.jpg`, `${LP}/confetti-life-4.jpg`, `${LP}/confetti-life-5.jpg`, `${LP}/confetti-life-6.jpg`],
  },
};
