// Shared color swatch definitions — used by ProductCard and ProductDetailClient.
// Keep these in sync with product.colors values from Shopify/localProducts.

export const PRODUCT_COLORS: Record<string, { name: string; value: string }[]> = {
  'trailblazing-fleece': [
    { name: 'Wildflower',  value: '#E8A0B8' },
    { name: 'Golden Hour', value: '#E8C84A' },
  ],
  'juniper-pant': [
    { name: 'Birch',       value: '#E4DCC8' },
    { name: 'Olive',       value: '#7A8352' },
  ],
  'alpine-baby-tee': [
    { name: 'Petal',       value: '#F2C4CE' },
    { name: 'Solstice',    value: '#D4A843' },
  ],
  // Order matches the image order in products.ts (berry → gingham → retro print)
  'sierra-shorts': [
    { name: 'Jam',      value: '#8E3A56' },
    { name: 'Picnic',   value: '#E7A6C0' },
    { name: 'Confetti', value: 'linear-gradient(135deg, #F2E9DA 0 25%, #A8C484 25% 50%, #7A5C3E 50% 75%, #E28FB4 75% 100%)' },
  ],
};

// Explicit gallery images per colorway (used when a product has different
// numbers of photos per color). Lead/front shot first.
const PP = '/images-2/model';

/**
 * The September 2026 studio shoot. Both folders are shot on white at
 * 2400x3600 — the same 2:3 as the set they replace, so the gallery geometry
 * is unchanged.
 *
 * The old /images-2/model files are still on disk and still used by the
 * lifestyle strip and the landing page, so nothing here is destructive: point
 * a list back at `${PP}/...` to restore any previous gallery.
 *
 * NOTE: scripts/import-product-photos.py no longer drives these lists. It
 * numbered files jam-1.jpg, jam-2.jpg ... in gallery order; these are hand
 * picked from a much larger take, so the filename numbers are the
 * photographer's, not a running order. Re-running that script will NOT
 * regenerate this.
 */
const SS = '/images-2/sierra-newest-shoot-pics';
const JS = '/images-2/juniper-newest-shoot-pics';

export const PRODUCT_COLOR_IMAGES: Record<string, Record<string, string[]>> = {
  /**
   * Order is the same for every colourway, because a shopper who flips
   * between them should not have the gallery rearrange under her:
   *
   *   1 front full   2 three-quarter   3 side   4 back   5-7 details
   */
  'sierra-shorts': {
    Jam: [
      `${SS}/sierra-jam2.jpg`,   // front, full length
      `${SS}/sierra-jam7.jpg`,   // three-quarter, hand on hip
      `${SS}/sierra-jam5.jpg`,   // side profile
      `${SS}/sierra-jam13.jpg`,  // back
      `${SS}/sierra-jam11.jpg`,  // waistband, held at the elastic
      `${SS}/sierra-jam15.jpg`,  // hem + woven label
      `${SS}/sierra-jam8.jpg`,   // folded forward — closes the set on movement
    ],
    Picnic: [
      `${SS}/sierra-picnic16.jpg`, // front, full length
      `${SS}/sierra-picnic11.jpg`, // three-quarter, hand on hip
      `${SS}/sierra-picnic13.jpg`, // side profile
      `${SS}/sierra-picnic5.jpg`,  // back
      `${SS}/sierra-picnic8.jpg`,  // waist-to-thigh, how it sits
      `${SS}/sierra-picnic2.jpg`,  // gingham close-up + woven label
    ],
    Confetti: [
      `${SS}/sierra-confetti9.jpg`, // front, full length
      `${SS}/sierra-confetti7.jpg`, // three-quarter, walking
      `${SS}/sierra-confetti6.jpg`, // side profile
      `${SS}/sierra-confetti3.jpg`, // back, three-quarter
      `${SS}/sierra-confetti2.jpg`, // back, close — the print at scale
      `${SS}/sierra-confetti0.jpg`, // pocket + woven label
    ],
  },
  'juniper-pant': {
    Birch: [
      `${JS}/birch-juniper2.jpg`,  // front, full length
      `${JS}/birch-juniper5.jpg`,  // three-quarter
      `${JS}/birch-juniper3.jpg`,  // side profile
      `${JS}/birch-juniper4.jpg`,  // back
      `${JS}/birch-juniper8.jpg`,  // fold-over waist + cargo pocket
      `${JS}/birch-juniper12.jpg`, // cargo pocket + woven label
      `${JS}/birch-juniper13.jpg`, // flare over the boot
    ],
    Olive: [
      `${JS}/olive-juniper0.jpg`,  // front, full length
      `${JS}/olive-juniper6.jpg`,  // three-quarter, hands in pockets
      `${JS}/olive-juniper2.jpg`,  // side profile
      `${JS}/olive-juniper7.jpg`,  // back
      `${JS}/olive-juniper4.jpg`,  // fold-over waist + cargo pocket
      `${JS}/olive-juniper9.jpg`,  // cargo pocket, opened
    ],
  },
};

// ─── Lifestyle strip ────────────────────────────────────────────────────────
//
// Outdoor shots — trail, rocks, a clothesline — shown in a small row further
// down the product page, under the description.
//
// Kept out of PRODUCT_COLOR_IMAGES on purpose. The main gallery is white-
// background studio frames whose job is to show the garment accurately; a
// backlit hillside dropped into that sequence makes the studio shots look
// inconsistent and the outdoor ones look like an accident. Separating them
// lets each do its own job.
//
// Generated by LIFESTYLE_PLAN in scripts/import-product-photos.py, at a
// smaller max edge than the gallery since these render as thumbnails.
const LP = '/images-2/lifestyle';
export const PRODUCT_LIFESTYLE_IMAGES: Record<string, Record<string, string[]>> = {
  'sierra-shorts': {
    Jam:      [`${LP}/jam-life-1.jpg`, `${LP}/jam-life-2.jpg`, `${LP}/jam-life-3.jpg`, `${LP}/jam-life-4.jpg`],
    Picnic:   [`${LP}/picnic-life-1.jpg`, `${LP}/picnic-life-2.jpg`, `${LP}/picnic-life-3.jpg`, `${LP}/picnic-life-4.jpg`, `${LP}/picnic-life-5.jpg`, `${LP}/picnic-life-6.jpg`],
    Confetti: [`${LP}/confetti-life-1.jpg`, `${LP}/confetti-life-2.jpg`, `${LP}/confetti-life-3.jpg`, `${LP}/confetti-life-4.jpg`, `${LP}/confetti-life-5.jpg`, `${LP}/confetti-life-6.jpg`],
  },
};
