import type { Metadata } from 'next';
import Script from 'next/script';
import { Inter, Playfair_Display, Montserrat, Great_Vibes, Ballet, Codystar, Cedarville_Cursive } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import AccessBanner from '@/components/AccessBanner';
import AttributionTracker from '@/components/AttributionTracker';
import WelcomePopup from '@/components/WelcomePopup';
import { KLAVIYO_COMPANY_ID } from '@/lib/klaviyo';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter', display: 'swap' });
const playfair = Playfair_Display({ subsets: ['latin'], variable: '--font-playfair', display: 'swap' });
const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-montserrat', display: 'swap' });
const greatVibes = Great_Vibes({ subsets: ['latin'], weight: '400', variable: '--font-script', display: 'swap' });
const ballet = Ballet({ subsets: ['latin'], variable: '--font-ballet', display: 'swap' });
const codystar = Codystar({ subsets: ['latin'], weight: '400', variable: '--font-codystar', display: 'swap' });
const cedarvilleCursive = Cedarville_Cursive({ subsets: ['latin'], weight: '400', variable: '--font-cedarville', display: 'swap' });

export const metadata: Metadata = {
  metadataBase: new URL('https://tualmi.com'),
  title: {
    default: 'Tualmi — actually cute hiking apparel',
    template: '%s | Tualmi',
  },
  description:
    'Hiking apparel made by women, for women — the fits, prints, and colorways the legacy brands never made. Built for the trail, cute everywhere else.',
  openGraph: {
    siteName: 'Tualmi',
    type: 'website',
    title: 'Tualmi — actually cute hiking apparel',
    description:
      'Hiking apparel made by women, for women — the fits, prints, and colorways the legacy brands never made.',
    // Default link preview for every page that doesn't set its own.
    // 1200x630, generated by scripts/make-og-images.py.
    images: [{ url: '/og/home-og.jpg', width: 1200, height: 630, alt: 'Tualmi — actually cute hiking apparel' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Tualmi — actually cute hiking apparel',
    description:
      'Hiking apparel made by women, for women — the fits, prints, and colorways the legacy brands never made.',
    images: ['/og/home-og.jpg'],
  },
  // Site-ownership verification tags. Next renders these into <head> on every
  // page, which is what the platforms crawl for.
  other: {
    // Pinterest — Settings → Claimed accounts → Claim website
    'p:domain_verify': '7209508abe4a03d0db9e62ce50ec661f',
  },
};

// Google Analytics 4 measurement ID. Loaded once here in the root layout, which
// wraps every route — do not add a second gtag snippet anywhere else.
const GA_MEASUREMENT_ID = 'G-PTRJN12KTL';

const organizationJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'Tualmi',
  url: 'https://tualmi.com',
  logo: 'https://tualmi.com/images-2/logo2-maroon.png',
  foundingDate: '2026',
  foundingLocation: {
    '@type': 'Place',
    address: { '@type': 'PostalAddress', addressRegion: 'CA', addressCountry: 'US' },
  },
  description:
    'Tualmi is a women-owned outdoor apparel brand making fashion-forward, trail-ready hiking gear for women. Every piece features women-specific, flattering fits — not adapted from men’s patterns — and is made from sustainable, recycled materials in a WRAP-certified facility. Based in California.',
  knowsAbout: [
    'women’s hiking apparel',
    'sustainable outdoor clothing',
    'fashion-forward trail gear',
    'recycled outdoor apparel',
  ],
  sameAs: [
    'https://www.tiktok.com/@tualmi.outdoors',
    'https://www.instagram.com/tualmioutdoors',
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${playfair.variable} ${montserrat.variable} ${greatVibes.variable} ${ballet.variable} ${codystar.variable} ${cedarvilleCursive.variable}`}>
      <body className="font-sans">
        {/* Google tag (gtag.js) — injected into <head> by next/script */}
        <Script
          id="ga4-src"
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`}
        />
        <Script id="ga4-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${GA_MEASUREMENT_ID}', {
              // Cross-domain: checkout lives on tualmi.myshopify.com, so without
              // this a shopper is counted as two users and the purchase is
              // attributed to a new "referral" session. This is the code half —
              // it must be paired with GA4 admin → Data Streams → Configure tag
              // settings → Configure your domains, listing both hosts.
              linker: {
                domains: ['tualmi.com', 'www.tualmi.com', 'tualmi.myshopify.com'],
                accept_incoming: true,
              },
            });
          `}
        </Script>
        {/* Klaviyo onsite tracking.

            This was never installed, which is why `Viewed Product` had fired
            zero times in Klaviyo and a browse-abandon flow was impossible to
            build — there was no browse event to trigger on. The events
            themselves are pushed from lib/klaviyo.ts via lib/analytics.ts.

            The company id is a public identifier; it appears in this script URL
            on every Klaviyo-enabled storefront. No private key belongs here. */}
        <Script
          id="klaviyo-onsite"
          strategy="afterInteractive"
          src={`https://static.klaviyo.com/onsite/js/klaviyo.js?company_id=${KLAVIYO_COMPANY_ID}`}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
        <AttributionTracker />
        <Header />
        <main className="min-h-screen">
          {children}
        </main>
        <Footer />
        {/* Fires 3s after load on mobile (or on first scroll), 1.2s on desktop.
            Shows once ever per browser; skipped on /invite, /cart, /discount. */}
        <WelcomePopup />
        <AccessBanner />
      </body>
    </html>
  );
}
